events {}
http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile      on;

    server {
        listen 8000;

        location /efserver {
            alias /usr/share/nginx/html/efserver.html;
        }

        location /processed {
            alias /usr/share/nginx/html/processed_1.html;
        }
    }
}
