events {}
http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile      on;

    server {
        listen 8000;

        # Serve efserver.html at the root path /
        location /efserver {
            alias /usr/share/nginx/html/efserver.html;
        }

        # Serve processed (1).html at the /processed path
        location /processed {
            alias /usr/share/nginx/html/processed(1).html;
        }
    }
}
